### ISSUE TITLE
ERROR @wdio/runner: Error: Some reporters are still unsynced: VideoReporter

### ISSUE THREAD

**Issue by Govind-Markad** [webdriverio-community/wdio-video-reporter#430] opened 2024-09-26 10:59 UTC
I am getting a blank video; there may be another window opening when the test starts(BiDi window with that one blank tab). I am new, so please correct me if I am wrong anywhere.

Log:
ERROR @wdio/runner: Error: Some reporters are still unsynced: VideoReporter
[0-0]     at Timeout.<anonymous> (file:///D:/automationPorject/Sample_Project/node_modules/@wdio/runner/build/index.js:561:25)
[0-0]     at listOnTimeout (node:internal/timers:573:17)
[0-0]     at process.processTimers (node:internal/timers:514:7)

To Reproduce :
https://github.com/Govind-Markad/Automation_Test

Expected behavior
There should be a recorded video of the test.
 - wdio-video-reporter version: 6.0.0
 - WebdriverIO version: 9.1.0
 - Mode: Local
 - Node.js version: v20
 - NPM version: 10.7.0
 - Browser name and version: Chrome 129.0.6668.60
 - Platform name and version: Windows 11

**Comment by christian-bromann** [comment] 2024-09-30 16:45
Duplicate of #133

**Closed by christian-bromann** 2024-09-30 16:45 UTC
Labels: bug, help wanted

**Comment by FluffyJay1** [comment] 2024-10-10 09:38
Don't think this is a duplicate of #133, this seems unique to WDIO v9 and I suspect it's to do with the switch to the new BiDi protocol. I am encountering this same issue, and when I add `wdio:enforceWebDriverClassic` to my config I no longer encounter this issue.

Diving into the `src/index.ts`, I've been able to narrow it down to specific promises in `screenshotPromises` never resolving. Specifically, it appears to be the last screenshot from each test. If I remove the last `this.addFrame()` calls in `onTestEnd` and `onSuiteEnd`, the problem goes away.

**Comment by brickfungus** [comment] 2024-10-10 14:57
@FluffyJay1 have you tried bumping up the `videoRenderTimeout` value.  it's in ms and noticed your original wdio.conf file had 120, which should probably be 120000 for 2 min

I'm working on some ideas to fix the blank frames at the end of tests
