### ISSUE TITLE
Request failed with status 404 due to no such alert: no such alert

### ISSUE THREAD

**Issue by brickfungus** [webdriverio-community/wdio-video-reporter#110] opened 2023-10-04 22:49 UTC
**Describe the bug**
Version 4.0.5 produces many warns & errors due to an alert not being present.  This doesn't happen in 4.0.4

**Log**
Please set `wdio.config.logLevel = 'debug'`, then post the whole file called `wdio-0-0-video-reporter.log`.
If it is very large, consider using a gist - http://gist.github.com.

**Expected behavior**
Shouldn't be getting that many error messages

**Environment (please complete the following information):**
 - **wdio-video-reporter version:** 4.0.5
 - **WebdriverIO version:** 8.16.20
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 18.18.0
 - **NPM version:** 10.2.0
 - **Browser name and version:** Chrome 117.0.5938.149
 - **Platform name and version:** Windows 11

![image](https://github.com/webdriverio-community/wdio-video-reporter/assets/3083282/4b722b7d-424f-42a5-a00d-83eff25338f1)
[wdio-0-0-Video-reporter.log](https://github.com/webdriverio-community/wdio-video-reporter/files/12810148/wdio-0-0-Video-reporter.log)

**Comment by Hamfri** [comment] 2023-10-09 09:03
I am also experiencing the same issue on macos-11, macos-13 and ubuntu 22.04. Most times the tests pass but whenever there is a call to 👇. The tests timeout and seem to be stuck in an endless loop that I have to end manually.

```
const initialWindow = await browser.getWindowHandle();
await browser.switchToWindow(initialWindow);
```
![Screenshot 2023-10-09 at 11 01 14](https://github.com/webdriverio-community/wdio-video-reporter/assets/3530884/7eee89cf-a7ca-41cc-96c7-17acb07d061c)

**Comment by erwinheitzman** [comment] 2023-10-09 11:01
These are webdriver errors and no actual error. The service should work fine

**Comment by erwinheitzman** [comment] 2023-10-09 11:13
Don't get me wrong, of course if the service does not work while getting these errors then please let me know but for now I am going to assume that the errors do not impact the functionality of the service.

Can anyone provide a reproducible example repo?

**Comment by DustinTheGreat** [comment] 2023-10-09 16:33
We are also started having this issue when adding the wdio-video-reporter.

wdio-video-reporter version: 4.0.5 and
WebdriverIO version: 8.16.0
Mode: Standalone
Node.js version: 18.16.1
NPM version: 9.5.1
Browser name and version: Chrome 117.0.5938.149
Platform name and version: Ubuntu 22

**Comment by erwinheitzman** [comment] 2023-10-09 23:10
These logs should only be used for debugging purposes but if you say that the amount of errors logged is way over the top, then the only option would be to remove the bug fix that was done to prevent issues for using the reporter when a pop-up is open.
Personally I feel that the user is responsible for dealing with this and not the reporter as a reporter should only.. well report.
That said it can happen that a pop-up is open at some unexpected time and that might cause issues, so it's a "pick your poison" type of case really.

**Comment by brickfungus** [comment] 2023-10-09 23:22
@erwinheitzman I don't agree... the fix in 4.0.4 didn't do this because it checked if the alert was even present first.  I know there was issues in edge with that, but I feel it could be mixed together to get best of both of those.

> These logs should only be used for debugging purposes 
They are, but when I do need to debug it's almost impossible to find what I need due to thousands of lines of errors thrown by video-reporter

**Comment by erwinheitzman** [comment] 2023-10-09 23:33
@brickfungus you can disagree but the only reason that that implementation did not throw errors was because it does not use the webdriver protocol (which you now see the errors of now that a proper cross browser webdriver implementation is used). The implementation achieves the same thing but webdriver sadly does not allow us to check for alerts without logging the error in the webdriver logs.

A few other options that come to mind are 1. we decrease the interval of the checks, thus decreasing the number of logs 2. We make the check for alert optional through a option that you can pass to the reporter disabling it if wanted

**Comment by erwinheitzman** [comment] 2023-10-09 23:49
@brickfungus i have made a suggestion to the team to also see if we can change the way the logs work and instead of logging the same message multiple times, we add a counter like so "Error: stale element (99)". I can't promise that we will do this or if it is doable but I did want to share it here 👍

**Comment by brickfungus** [comment] 2023-10-10 21:27
`isAlertOpen()` is chromium specific... I understand now.  
I'll play around and see if I can get some code that works.

**Comment by brickfungus** [comment] 2023-10-19 23:19
It's not my favorite solution, but it would at least cut the noise down for chrome runs.

```javascript
    // Skips screenshot if alert is displayed
    if (browser.isAlertOpen) {
      return browser.isAlertOpen().then((result) => {
        if (!result) {
          return this.addFrame();
        }

        return helpers.debugLog(
          'Skipped screenshot to avoid unexpected alert closing\n'
        );
      });
    } else {
      return browser
        .getAlertText()
        .then(() => {
          helpers.debugLog(
            'Skipped screenshot to avoid unexpected alert closing\n'
          );
        })
        .catch(() => {
          this.addFrame();
        });
    }
````

**Comment by erwinheitzman** [comment] 2023-10-19 23:48
@brickfungus thank you for looking into this. That code would solve it only for Chromium based browsers but it does help for those browsers indeed.

Could you checkout all the suggestions I did previously because some of these can be combined (also with your suggestion) and easily be implemented to also reduce the noise.

I am currently in the middle of a huge migration at work that is about to end after which I have time to pick this up 👍

**Comment by HedgU4** [comment] 2023-11-08 18:03
> ```js
>    if (browser.isAlertOpen) {
>       return browser.isAlertOpen().then((result) => {
>         if (!result) {
>           return this.addFrame();
>         }
> 
>         return helpers.debugLog(
>           'Skipped screenshot to avoid unexpected alert closing\n'
>         );
>       });
>     } else {
>       return browser
>         .getAlertText()
>         .then(() => {
>           helpers.debugLog(
>             'Skipped screenshot to avoid unexpected alert closing\n'
>           );
>         })
>         .catch(() => {
>           this.addFrame();
>         });
>     }
> ```

but not for firefox

**Comment by kamalbasnet95** [comment] 2023-11-23 15:13
I was also running into this. Looks like v4.0.4 seem to not throw any noise.

**Comment by erwinheitzman** [comment] 2023-12-01 10:01
The solution that @brickfungus provided is correct and can be used (apologies @brickfungus for not realising earlier, not sure why I thought it wouldn't work back then). Contributions are appreciated, this is after all an open source project 👍

**Comment by HedgU4** [comment] 2023-12-07 13:48
> The solution that @brickfungus provided is correct and can be used (apologies @brickfungus for not realising earlier, not sure why I thought it wouldn't work back then). Contributions are appreciated, this is after all an open source project 👍

What about firefox?

**Comment by christian-bromann** [comment] 2024-01-03 03:15
We are working on a fix for this which should be released with the next major version v5 of this reporter. We don't have any eta when this will happen though, hopefully within the next days.

**Comment by aaggarwal-sumo** [comment] 2024-01-31 08:13
Is this issue fixed in 5.1.3?

**Comment by brickfungus** [comment] 2024-01-31 17:06
@aaggarwal-sumo It seems to be, but there are other issues.  
@christian-bromann I think this can be closed, this seems to be fixed in V5

**Closed** 2024-01-31 17:07 UTC

**Comment by aaggarwal-sumo** [comment] 2024-01-31 17:50
what are the other issues?

**Comment by brickfungus** [comment] 2024-01-31 18:03
@aaggarwal-sumo check the other recent issues
